services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/comic_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 23370000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: comic_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23370000
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: